
import { Product, ProductStatus } from './types';

export const mockProducts: Product[] = [
    {
        id: 1,
        name: 'Hydrating Face Serum',
        description: 'A lightweight serum that deeply hydrates and plumps the skin.',
        category: 'Skincare',
        volume: '30ml',
        price: 25.00,
        status: 'in_stock',
        image: 'https://picsum.photos/seed/serum/400/400',
    },
    {
        id: 2,
        name: 'Vitamin C Brightening Cream',
        description: 'Boosts radiance and evens out skin tone for a healthy glow.',
        category: 'Skincare',
        volume: '50ml',
        price: 32.50,
        status: 'in_stock',
        image: 'https://picsum.photos/seed/cream/400/400',
    },
    {
        id: 3,
        name: 'Gentle Cleansing Foam',
        description: 'A soft foam that removes impurities without stripping the skin.',
        category: 'Skincare',
        volume: '150ml',
        price: 18.00,
        status: 'out_of_stock',
        image: 'https://picsum.photos/seed/foam/400/400',
    },
    {
        id: 4,
        name: 'Long-Lasting Matte Lipstick',
        description: 'Vibrant color with a comfortable, non-drying matte finish.',
        category: 'Makeup',
        volume: '3.5g',
        price: 22.00,
        status: 'in_stock',
        image: 'https://picsum.photos/seed/lipstick/400/400',
    },
    {
        id: 5,
        name: 'Volumizing Mascara',
        description: 'Lifts and thickens lashes for a dramatic, wide-eyed look.',
        category: 'Makeup',
        volume: '10ml',
        price: 19.50,
        status: 'in_stock',
        image: 'https://picsum.photos/seed/mascara/400/400',
    },
    {
        id: 6,
        name: 'HD Liquid Foundation',
        description: 'A buildable foundation for a flawless, natural-looking complexion.',
        category: 'Makeup',
        volume: '30ml',
        price: 35.00,
        status: 'in_stock',
        image: 'https://picsum.photos/seed/foundation/400/400',
    },
    {
        id: 7,
        name: 'Hidden Concealer Stick',
        description: 'This product is not visible to customers.',
        category: 'Makeup',
        volume: '5g',
        price: 15.00,
        status: 'hidden',
        image: 'https://picsum.photos/seed/concealer/400/400',
    },
    {
        id: 8,
        name: 'Repairing Hair Mask',
        description: 'Deeply conditions and restores dry, damaged hair.',
        category: 'Haircare',
        volume: '200ml',
        price: 28.00,
        status: 'in_stock',
        image: 'https://picsum.photos/seed/hairmask/400/400',
    },
    {
        id: 9,
        name: 'Nourishing Shampoo',
        description: 'Gently cleanses while adding moisture and shine.',
        category: 'Haircare',
        volume: '250ml',
        price: 16.00,
        status: 'in_stock',
        image: 'https://picsum.photos/seed/shampoo/400/400',
    },
     {
        id: 10,
        name: 'Exfoliating Body Scrub',
        description: 'Buffs away dead skin cells for smooth, radiant skin.',
        category: 'Bodycare',
        volume: '200g',
        price: 24.00,
        status: 'in_stock',
        image: 'https://picsum.photos/seed/scrub/400/400',
    },
    {
        id: 11,
        name: 'Rich Body Butter',
        description: 'Intensely moisturizes and nourishes dry skin.',
        category: 'Bodycare',
        volume: '150ml',
        price: 26.50,
        status: 'out_of_stock',
        image: 'https://picsum.photos/seed/butter/400/400',
    },
];
