
import { Product, ProductStatus } from './types';

export const mockProducts: Product[] = [
    {
        id: 1,
        name: 'Увлажняющая сыворотка для лица',
        description: 'Легкая сыворотка, которая глубоко увлажняет и придает коже упругость.',
        category: 'Уход за кожей',
        volume: '30ml',
        price: 25.00,
        status: 'in_stock',
        image: 'https://picsum.photos/seed/serum/400/400',
    },
    {
        id: 2,
        name: 'Осветляющий крем с витамином C',
        description: 'Придает коже сияние и выравнивает тон для здорового блеска.',
        category: 'Уход за кожей',
        volume: '50ml',
        price: 32.50,
        status: 'in_stock',
        image: 'https://picsum.photos/seed/cream/400/400',
    },
    {
        id: 3,
        name: 'Нежная очищающая пенка',
        description: 'Мягко удаляет загрязнения, не пересушивая кожу.',
        category: 'Уход за кожей',
        volume: '150ml',
        price: 18.00,
        status: 'out_of_stock',
        image: 'https://picsum.photos/seed/foam/400/400',
    },
    {
        id: 4,
        name: 'Стойкая матовая помада',
        description: 'Яркий цвет с комфортным матовым покрытием без ощущения сухости.',
        category: 'Макияж',
        volume: '3.5g',
        price: 22.00,
        status: 'in_stock',
        image: 'https://picsum.photos/seed/lipstick/400/400',
    },
    {
        id: 5,
        name: 'Объемная тушь для ресниц',
        description: 'Поднимает и утолщает ресницы, создавая эффект распахнутого взгляда.',
        category: 'Макияж',
        volume: '10ml',
        price: 19.50,
        status: 'in_stock',
        image: 'https://picsum.photos/seed/mascara/400/400',
    },
    {
        id: 6,
        name: 'Тональная основа HD',
        description: 'Слоистое покрытие для безупречного и естественного тона кожи.',
        category: 'Макияж',
        volume: '30ml',
        price: 35.00,
        status: 'in_stock',
        image: 'https://picsum.photos/seed/foundation/400/400',
    },
    {
        id: 7,
        name: 'Скрытый консилер-стик',
        description: 'Этот продукт не отображается для покупателей.',
        category: 'Макияж',
        volume: '5g',
        price: 15.00,
        status: 'hidden',
        image: 'https://picsum.photos/seed/concealer/400/400',
    },
    {
        id: 8,
        name: 'Восстанавливающая маска для волос',
        description: 'Глубоко питает и восстанавливает сухие, поврежденные волосы.',
        category: 'Уход за волосами',
        volume: '200ml',
        price: 28.00,
        status: 'in_stock',
        image: 'https://picsum.photos/seed/hairmask/400/400',
    },
    {
        id: 9,
        name: 'Питательный шампунь',
        description: 'Бережно очищает, придавая волосам мягкость и блеск.',
        category: 'Уход за волосами',
        volume: '250ml',
        price: 16.00,
        status: 'in_stock',
        image: 'https://picsum.photos/seed/shampoo/400/400',
    },
    {
        id: 10,
        name: 'Отшелушивающий скраб для тела',
        description: 'Удаляет ороговевшие клетки, делая кожу гладкой и сияющей.',
        category: 'Уход за телом',
        volume: '200g',
        price: 24.00,
        status: 'in_stock',
        image: 'https://picsum.photos/seed/scrub/400/400',
    },
    {
        id: 11,
        name: 'Плотный крем-баттер для тела',
        description: 'Интенсивно увлажняет и питает сухую кожу.',
        category: 'Уход за телом',
        volume: '150ml',
        price: 26.50,
        status: 'out_of_stock',
        image: 'https://picsum.photos/seed/butter/400/400',
    },
];
